### ISSUE TITLE
Rename repo geomessage-simulator-qt

### ISSUE THREAD

**Issue by csmoore** [Esri/geomessage-simulator-qt#18]
Just to make this name consistent with how it is used elsewhere

Perhaps also rename the app exe from ArcGISQtMessageSimulator (its name from way back in the day) to geomessage-simulator

**Comment by garys-esri** [comment]
I'm fine with renaming the repo again. That's easy. And yes, we can rename the app. The ops-server release team will have to search and replace in their scripts, but I think that's a small price to pay for a more meaningful .exe name.
