### ISSUE TITLE
Provide a stand-alone deployment for Windows/Linux

### ISSUE THREAD

**Issue by csmoore** [Esri/geomessage-simulator-qt#19]
The current instructions instruct you to get the full VehicleCommander deployment (weighing in at 500-800MB or so) in order to get a stand-alone deployed version of the geomessage-simulator.

Provide a standalone zipped deployment of just the simulator somewhere ex: 

* in this repo in an "application" or "deployment" folder
* or as a link to an ArcGIS portal item

**Comment by garys-esri** [comment]
It will be a portal item on ArcGIS.com.

**Comment by garys-esri** [comment]
In addition to posting the stand-alone app as an ArcGIS Online item, we need to link to it from Vehicle Commander and Squad Leader repos and app items.

**Comment by garys-esri** [comment]
The code changes are in #23. We still need to get the binary distros posted. I will push for that to happen and leave this issue assigned to me for now. After that, I'll assign this issue to @csmoore to verify and close.

**Comment by jrweakland** [comment]
@csmoore Verify and close please.

**Comment by csmoore** [comment]
I have seen the downloads - it may take a bit for them to be placed on http://www.esri.com/apps/products/download/index.cfm#ArcGIS_for_the_Military

Just a reminder to myself here for later in case it isn't discussed elsewhere - the reason for the x86 and x64 app deployment versions is the Qt-> C standard/runtime library dependencies (Linux) & Visual C++ Redistributable dependencies (Windows)
